<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ank.DocToolkit" Version="[0.2.1, )" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\tests\DocToolkit.Tests\assets\sample.pptx" Link="assets\sample.pptx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
