using DocToolkit;
using DocToolkit.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace WorkerService;

/// <summary>
/// A background job that renders a report and writes it to disk — the shape of every "nightly
/// export" this library ends up in.
/// </summary>
/// <remarks>
/// The point of this sample is the constructor. A <see cref="BackgroundService"/> is registered as
/// a singleton, so the standard advice is that it cannot take a dependency directly and must open
/// an <c>IServiceScope</c> per unit of work. That advice exists because <c>DbContext</c> and
/// friends are scoped, and capturing a scoped service in a singleton either throws at startup or —
/// worse — hands you one instance for the lifetime of the process.
///
/// It does not apply here. Everything <c>AddDocToolkit</c> registers is a stateless singleton:
/// each method takes its input and returns its output, holding nothing between calls. So these
/// inject straight into the worker, and the scope dance would be pure ceremony.
///
/// <see cref="IOptionsMonitor{T}"/> is the exception worth keeping. The services read their options
/// through it on every call rather than capturing them, so a configuration change reaches a
/// long-running worker without a restart — which matters far more in a process that runs for weeks
/// than in a request that lasts 40 ms.
/// </remarks>
#region worker
internal sealed class ReportWorker(
    IDocxEditor documents,
    IDocxToPdfConverter pdf,
    IWorkbookEditor workbooks,
    IOptionsMonitor<DocToolkitOptions> options,
    IHostApplicationLifetime lifetime,
    ILogger<ReportWorker> logger) : BackgroundService
#endregion
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var outputDirectory = Path.Join(AppContext.BaseDirectory, "reports");
        Directory.CreateDirectory(outputDirectory);

        logger.LogInformation(
            "Remote images are {State} — read from IOptionsMonitor at the moment of use, so "
            + "changing it in configuration takes effect on the next run without a restart.",
            options.CurrentValue.AllowRemoteImageDownload ? "enabled" : "disabled");

        var rows = new object?[][]
        {
            ["Region", "Revenue", "Change"],
            ["EMEA", 1_200, "+4%"],
            ["APAC", 980, "-1%"],
            ["AMER", 1_450, "+9%"],
        };

        // A workbook for the people who will pivot it, and a PDF for the people who will read it.
        // Both from the same numbers, which is the reason a job like this exists at all.
        var workbookPath = Path.Join(outputDirectory, "revenue.xlsx");
        await using (var destination = File.Create(workbookPath))
        {
            await workbooks.CreateAsync("Revenue", rows, destination, stoppingToken);
        }

        var report = documents.Create(
            [
                DocxBlock.Heading("Revenue report", 1),
                DocxBlock.Paragraph("Generated by a background service. No Word, no browser, no interop."),
                DocxBlock.Table(["Region", "Revenue", "Change"], rows.Skip(1)),
            ],
            PageSetup.A4.WithMargins(54));

        var pdfPath = Path.Join(outputDirectory, "revenue.pdf");
        await File.WriteAllBytesAsync(pdfPath, pdf.Convert(report), stoppingToken);

        logger.LogInformation("Wrote {Workbook} and {Pdf}", workbookPath, pdfPath);

        // A real worker would loop on a timer or a queue. This one has finished its only unit of
        // work, so it stops the host rather than idling — `dotnet run` should return.
        lifetime.StopApplication();
    }
}
