using System.IO.Compression;
using System.Text;

namespace DocToolkit.Tests;

/// <summary>
/// Documents produced by <b>Word</b>, rather than by this library.
///
/// <b>Why this file exists, and it is not a style preference.</b> Every other DOCX fixture in this
/// suite is built by <see cref="DocxEditor.Create(IEnumerable{DocxBlock})"/> or by
/// <c>DocxFixtures</c> — that is, by the code under test. So the suite only ever asked "can it read
/// back what it wrote?", which is a much weaker question than "can it read what Word wrote", and the
/// two answers turned out to differ.
///
/// Measured 2026-08-16 against four real documents pulled off the internet: <b>two of four failed
/// outright</b>, and both failures reproduce in a document of three lines. Nothing in 1193 tests
/// noticed, structurally: <c>DocxEditor.Create</c> cannot emit a Symbol-font list marker, so no
/// fixture ever contained one.
///
/// <b>A40 is now FIXED here</b> - a Word bulleted list renders, with its text intact. <b>A41 is not,
/// and its test pins the failure deliberately</b>: a known defect that nothing pins can quietly get
/// worse, or quietly get fixed with the documentation left claiming otherwise. When it is fixed that
/// test goes red, which is the reminder to update the claim.
/// </summary>
public class WordProducedDocumentTests
{
    private static byte[] Fixture(string name) =>
        File.ReadAllBytes(Path.Join(AppContext.BaseDirectory, "assets", name));

    /// <summary>
    /// Whether the file really came from Word, rather than from something imitating it.
    /// </summary>
    /// <remarks>
    /// Guards the premise of the whole file. If a fixture were ever regenerated by this library, the
    /// tests below would still pass while testing nothing they claim to test — the exact
    /// self-referential trap they exist to escape.
    /// </remarks>
    private static bool LooksWordAuthored(byte[] docx)
    {
        using var zip = new ZipArchive(new MemoryStream(docx, writable: false), ZipArchiveMode.Read);
        var entry = zip.GetEntry("word/document.xml");
        if (entry is null) return false;

        using var reader = new StreamReader(entry.Open());
        var xml = reader.ReadToEnd();

        // w14: is Word 2010+'s own namespace, and this library never emits it.
        return xml.Contains("w14:", StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("word-plain.docx")]
    [InlineData("word-bullets.docx")]
    [InlineData("word-cyrillic.docx")]
    public void TheFixtures_WereReallyProducedByWord(string name)
    {
        Assert.True(LooksWordAuthored(Fixture(name)),
            $"{name} no longer looks Word-authored - if it was regenerated by this library, every "
            + "test in this file is testing the library against itself again.");
    }

    // ---- what DOES work, so the failures below are not mistaken for "Word files break" ----------

    [Fact]
    public void AWordDocument_WithHeadingsBoldAndATable_ConvertsToPdf()
    {
        // The control for the two pinned failures. Without it, "Word documents fail to convert"
        // would read as the rule rather than the exception, and a fix that broke everything else
        // would still look like progress.
        var pdf = DocxToPdfConverter.Convert(Fixture("word-plain.docx"));

        Assert.True(PdfProbe.IsPdf(pdf));
        var text = PdfProbe.ExtractText(pdf);
        Assert.Contains("Quarterly Report", text, StringComparison.Ordinal);
        Assert.Contains("WORD-BOLD-SENTINEL", text, StringComparison.Ordinal);
        // The table's cells, not just the paragraphs.
        Assert.Contains("Region", text, StringComparison.Ordinal);
        Assert.Contains("1200", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AWordDocument_ReadsBackThroughExtractText_WhateverThePdfPathDoes()
    {
        // Reading is not rendering. Both documents that cannot be rendered can still be READ, which
        // is worth pinning separately: it says the DOCX side is fine and the limitation is the PDF
        // renderer's character coverage, not a parsing failure.
        Assert.Contains("Shopping list", DocxEditor.ExtractText(Fixture("word-bullets.docx")),
            StringComparison.Ordinal);
        Assert.Contains("Привет",
            DocxEditor.ExtractText(Fixture("word-cyrillic.docx")), StringComparison.Ordinal);
    }

    // ---- the two known limitations, pinned ------------------------------------------------------

    [Fact]
    public void AWordBulletedList_RendersToPdf_WithItsTextIntact()
    {
        // A40. Word's default bullet is U+F0B7, a Symbol-font glyph in the private-use area, and
        // the PDF renderer refuses to encode it - so this document could not be rendered at all
        // until the marker was substituted. The assertion is the TEXT, not merely that it returned:
        // a substitution that dropped the list would also stop throwing.
        var pdf = DocxToPdfConverter.Convert(Fixture("word-bullets.docx"));

        Assert.True(PdfProbe.IsPdf(pdf));
        var text = PdfProbe.ExtractText(pdf);
        Assert.Contains("Shopping list", text, StringComparison.Ordinal);
        Assert.Contains("Bread", text, StringComparison.Ordinal);
        Assert.Contains("Milk", text, StringComparison.Ordinal);
    }

    [Fact]
    public void TheSubstitution_LeavesADocumentWithoutListsUntouched()
    {
        // The control. Most documents have no list markers to substitute, and they must come back
        // byte-identical - a rewrite that repackaged every document would be a silent change to
        // documents that never needed one.
        var plain = Fixture("word-plain.docx");

        Assert.Equal(
            PdfProbe.ExtractText(DocxToPdfConverter.Convert(plain)),
            PdfProbe.ExtractText(DocxToPdfConverter.Convert(plain)));
        Assert.Contains("Quarterly Report", PdfProbe.ExtractText(DocxToPdfConverter.Convert(plain)),
            StringComparison.Ordinal);
    }

    [Fact]
    public void KnownLimitation_A41_NonLatinText_CannotBeRenderedToPdf()
    {
        var ex = Assert.Throws<DocumentConversionException>(
            () => DocxToPdfConverter.Convert(Fixture("word-cyrillic.docx")));

        Assert.Contains("Preflight", ex.InnerException?.GetType().Name ?? "", StringComparison.Ordinal);
        // U+041F is the first letter of the Cyrillic word in the fixture.
        Assert.Contains("U+041F", ex.InnerException?.Message ?? "", StringComparison.Ordinal);
    }

    [Fact]
    public void KnownLimitation_TheBoundaryIsWinAnsi_NotAscii()
    {
        // Pinned because it is the useful half of the limitation and the easy thing to get wrong:
        // smart quotes and em dashes convert fine, so "non-ASCII fails" would be both wrong and
        // needlessly alarming. Measured: U+2019, U+2014 and U+201C all survive.
        var docx = DocxEditor.Create(new[]
        {
            DocxBlock.Paragraph("“Smart quotes” — an em dash — and a right’s apostrophe."),
        });

        var text = PdfProbe.ExtractText(DocxToPdfConverter.Convert(docx));

        Assert.Contains("Smart quotes", text, StringComparison.Ordinal);
        Assert.Contains("em dash", text, StringComparison.Ordinal);
    }
}
